version: '3'

services:
  postgres1:
    image: postgres:13
    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres1_data:/var/lib/postgresql/data

  postgres2:
    image: postgres:13
    environment:
      POSTGRES_DB: orders_eur_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - postgres2_data:/var/lib/postgresql/data

  airflow-init:
    build: .
    depends_on:
      - postgres1
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://user:password@postgres1:5432/orders_db
      AIRFLOW__WEBSERVER__SECRET_KEY: secret_key_2025
    entrypoint: >
      /bin/bash -c "
      airflow db init &&
      airflow users create --username candidate --password 123 --firstname Test --lastname User --role Admin --email tonkksenia@gmail.com"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./requirements.txt:/requirements.txt

  airflow-webserver:
    build: .
    env_file:
      - .env
    depends_on:
      - airflow-init
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://user:password@postgres1:5432/orders_db
      AIRFLOW__WEBSERVER__SECRET_KEY: secret_key_2025
    command: webserver
    volumes:
      - ./dags:/opt/airflow/dags
      - ./requirements.txt:/requirements.txt

  airflow-scheduler:
    build: .
    env_file:
      - .env
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://user:password@postgres1:5432/orders_db
      AIRFLOW__WEBSERVER__SECRET_KEY: secret_key_2025
    command: scheduler
    volumes:
      - ./dags:/opt/airflow/dags
      - ./requirements.txt:/requirements.txt

volumes:
  postgres1_data:
  postgres2_data: